//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SimuladorP360.WsAluno {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsAlunoSoap", Namespace="ABEC.SIGA.WEBSERVICE")]
    public partial class WsAluno : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ManterAlunoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterAlunoSigaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterSituacaoFinanceiraOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterLinkContratoAlunoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PagarLinkPagamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TrocarCartaoLinkPagamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PagarParcelaEspecificaLinkPagamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PagarBoletoVencidoCartaoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsAluno() {
            this.Url = global::SimuladorP360.Properties.Settings.Default.SimuladorP360_WsAluno_WsAluno;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ManterAlunoCompletedEventHandler ManterAlunoCompleted;
        
        /// <remarks/>
        public event ObterAlunoSigaCompletedEventHandler ObterAlunoSigaCompleted;
        
        /// <remarks/>
        public event ObterSituacaoFinanceiraCompletedEventHandler ObterSituacaoFinanceiraCompleted;
        
        /// <remarks/>
        public event ObterLinkContratoAlunoCompletedEventHandler ObterLinkContratoAlunoCompleted;
        
        /// <remarks/>
        public event PagarLinkPagamentoCompletedEventHandler PagarLinkPagamentoCompleted;
        
        /// <remarks/>
        public event TrocarCartaoLinkPagamentoCompletedEventHandler TrocarCartaoLinkPagamentoCompleted;
        
        /// <remarks/>
        public event PagarParcelaEspecificaLinkPagamentoCompletedEventHandler PagarParcelaEspecificaLinkPagamentoCompleted;
        
        /// <remarks/>
        public event PagarBoletoVencidoCartaoCompletedEventHandler PagarBoletoVencidoCartaoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ABEC.SIGA.WEBSERVICE/ManterAluno", RequestNamespace="ABEC.SIGA.WEBSERVICE", ResponseNamespace="ABEC.SIGA.WEBSERVICE", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ManterAluno(AlunoDTO aluno) {
            object[] results = this.Invoke("ManterAluno", new object[] {
                        aluno});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ManterAlunoAsync(AlunoDTO aluno) {
            this.ManterAlunoAsync(aluno, null);
        }
        
        /// <remarks/>
        public void ManterAlunoAsync(AlunoDTO aluno, object userState) {
            if ((this.ManterAlunoOperationCompleted == null)) {
                this.ManterAlunoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnManterAlunoOperationCompleted);
            }
            this.InvokeAsync("ManterAluno", new object[] {
                        aluno}, this.ManterAlunoOperationCompleted, userState);
        }
        
        private void OnManterAlunoOperationCompleted(object arg) {
            if ((this.ManterAlunoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ManterAlunoCompleted(this, new ManterAlunoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ABEC.SIGA.WEBSERVICE/ObterAlunoSiga", RequestNamespace="ABEC.SIGA.WEBSERVICE", ResponseNamespace="ABEC.SIGA.WEBSERVICE", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObterAlunoSiga(string Cpf) {
            object[] results = this.Invoke("ObterAlunoSiga", new object[] {
                        Cpf});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObterAlunoSigaAsync(string Cpf) {
            this.ObterAlunoSigaAsync(Cpf, null);
        }
        
        /// <remarks/>
        public void ObterAlunoSigaAsync(string Cpf, object userState) {
            if ((this.ObterAlunoSigaOperationCompleted == null)) {
                this.ObterAlunoSigaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterAlunoSigaOperationCompleted);
            }
            this.InvokeAsync("ObterAlunoSiga", new object[] {
                        Cpf}, this.ObterAlunoSigaOperationCompleted, userState);
        }
        
        private void OnObterAlunoSigaOperationCompleted(object arg) {
            if ((this.ObterAlunoSigaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterAlunoSigaCompleted(this, new ObterAlunoSigaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ABEC.SIGA.WEBSERVICE/ObterSituacaoFinanceira", RequestNamespace="ABEC.SIGA.WEBSERVICE", ResponseNamespace="ABEC.SIGA.WEBSERVICE", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SituacaoFinanceiraAlunoDTO[] ObterSituacaoFinanceira(int idEmpresa, int idContrato) {
            object[] results = this.Invoke("ObterSituacaoFinanceira", new object[] {
                        idEmpresa,
                        idContrato});
            return ((SituacaoFinanceiraAlunoDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void ObterSituacaoFinanceiraAsync(int idEmpresa, int idContrato) {
            this.ObterSituacaoFinanceiraAsync(idEmpresa, idContrato, null);
        }
        
        /// <remarks/>
        public void ObterSituacaoFinanceiraAsync(int idEmpresa, int idContrato, object userState) {
            if ((this.ObterSituacaoFinanceiraOperationCompleted == null)) {
                this.ObterSituacaoFinanceiraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterSituacaoFinanceiraOperationCompleted);
            }
            this.InvokeAsync("ObterSituacaoFinanceira", new object[] {
                        idEmpresa,
                        idContrato}, this.ObterSituacaoFinanceiraOperationCompleted, userState);
        }
        
        private void OnObterSituacaoFinanceiraOperationCompleted(object arg) {
            if ((this.ObterSituacaoFinanceiraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterSituacaoFinanceiraCompleted(this, new ObterSituacaoFinanceiraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ABEC.SIGA.WEBSERVICE/ObterLinkContratoAluno", RequestNamespace="ABEC.SIGA.WEBSERVICE", ResponseNamespace="ABEC.SIGA.WEBSERVICE", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LinkContratoDTO ObterLinkContratoAluno(int idEmpresa, int idAluno, string idTurma) {
            object[] results = this.Invoke("ObterLinkContratoAluno", new object[] {
                        idEmpresa,
                        idAluno,
                        idTurma});
            return ((LinkContratoDTO)(results[0]));
        }
        
        /// <remarks/>
        public void ObterLinkContratoAlunoAsync(int idEmpresa, int idAluno, string idTurma) {
            this.ObterLinkContratoAlunoAsync(idEmpresa, idAluno, idTurma, null);
        }
        
        /// <remarks/>
        public void ObterLinkContratoAlunoAsync(int idEmpresa, int idAluno, string idTurma, object userState) {
            if ((this.ObterLinkContratoAlunoOperationCompleted == null)) {
                this.ObterLinkContratoAlunoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterLinkContratoAlunoOperationCompleted);
            }
            this.InvokeAsync("ObterLinkContratoAluno", new object[] {
                        idEmpresa,
                        idAluno,
                        idTurma}, this.ObterLinkContratoAlunoOperationCompleted, userState);
        }
        
        private void OnObterLinkContratoAlunoOperationCompleted(object arg) {
            if ((this.ObterLinkContratoAlunoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterLinkContratoAlunoCompleted(this, new ObterLinkContratoAlunoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ABEC.SIGA.WEBSERVICE/PagarLinkPagamento", RequestNamespace="ABEC.SIGA.WEBSERVICE", ResponseNamespace="ABEC.SIGA.WEBSERVICE", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PagarLinkPagamento(int idEmpresa, int idAluno, string idTurma, Cartao cartao) {
            object[] results = this.Invoke("PagarLinkPagamento", new object[] {
                        idEmpresa,
                        idAluno,
                        idTurma,
                        cartao});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PagarLinkPagamentoAsync(int idEmpresa, int idAluno, string idTurma, Cartao cartao) {
            this.PagarLinkPagamentoAsync(idEmpresa, idAluno, idTurma, cartao, null);
        }
        
        /// <remarks/>
        public void PagarLinkPagamentoAsync(int idEmpresa, int idAluno, string idTurma, Cartao cartao, object userState) {
            if ((this.PagarLinkPagamentoOperationCompleted == null)) {
                this.PagarLinkPagamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPagarLinkPagamentoOperationCompleted);
            }
            this.InvokeAsync("PagarLinkPagamento", new object[] {
                        idEmpresa,
                        idAluno,
                        idTurma,
                        cartao}, this.PagarLinkPagamentoOperationCompleted, userState);
        }
        
        private void OnPagarLinkPagamentoOperationCompleted(object arg) {
            if ((this.PagarLinkPagamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PagarLinkPagamentoCompleted(this, new PagarLinkPagamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ABEC.SIGA.WEBSERVICE/TrocarCartaoLinkPagamento", RequestNamespace="ABEC.SIGA.WEBSERVICE", ResponseNamespace="ABEC.SIGA.WEBSERVICE", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TrocarCartaoLinkPagamento(int idEmpresa, int idAluno, string idTurma, Cartao cartao, int numParcela) {
            object[] results = this.Invoke("TrocarCartaoLinkPagamento", new object[] {
                        idEmpresa,
                        idAluno,
                        idTurma,
                        cartao,
                        numParcela});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TrocarCartaoLinkPagamentoAsync(int idEmpresa, int idAluno, string idTurma, Cartao cartao, int numParcela) {
            this.TrocarCartaoLinkPagamentoAsync(idEmpresa, idAluno, idTurma, cartao, numParcela, null);
        }
        
        /// <remarks/>
        public void TrocarCartaoLinkPagamentoAsync(int idEmpresa, int idAluno, string idTurma, Cartao cartao, int numParcela, object userState) {
            if ((this.TrocarCartaoLinkPagamentoOperationCompleted == null)) {
                this.TrocarCartaoLinkPagamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrocarCartaoLinkPagamentoOperationCompleted);
            }
            this.InvokeAsync("TrocarCartaoLinkPagamento", new object[] {
                        idEmpresa,
                        idAluno,
                        idTurma,
                        cartao,
                        numParcela}, this.TrocarCartaoLinkPagamentoOperationCompleted, userState);
        }
        
        private void OnTrocarCartaoLinkPagamentoOperationCompleted(object arg) {
            if ((this.TrocarCartaoLinkPagamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrocarCartaoLinkPagamentoCompleted(this, new TrocarCartaoLinkPagamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ABEC.SIGA.WEBSERVICE/PagarParcelaEspecificaLinkPagamento", RequestNamespace="ABEC.SIGA.WEBSERVICE", ResponseNamespace="ABEC.SIGA.WEBSERVICE", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PagarParcelaEspecificaLinkPagamento(int idEmpresa, int idAluno, string idTurma, Cartao cartao, int numParcela) {
            object[] results = this.Invoke("PagarParcelaEspecificaLinkPagamento", new object[] {
                        idEmpresa,
                        idAluno,
                        idTurma,
                        cartao,
                        numParcela});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PagarParcelaEspecificaLinkPagamentoAsync(int idEmpresa, int idAluno, string idTurma, Cartao cartao, int numParcela) {
            this.PagarParcelaEspecificaLinkPagamentoAsync(idEmpresa, idAluno, idTurma, cartao, numParcela, null);
        }
        
        /// <remarks/>
        public void PagarParcelaEspecificaLinkPagamentoAsync(int idEmpresa, int idAluno, string idTurma, Cartao cartao, int numParcela, object userState) {
            if ((this.PagarParcelaEspecificaLinkPagamentoOperationCompleted == null)) {
                this.PagarParcelaEspecificaLinkPagamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPagarParcelaEspecificaLinkPagamentoOperationCompleted);
            }
            this.InvokeAsync("PagarParcelaEspecificaLinkPagamento", new object[] {
                        idEmpresa,
                        idAluno,
                        idTurma,
                        cartao,
                        numParcela}, this.PagarParcelaEspecificaLinkPagamentoOperationCompleted, userState);
        }
        
        private void OnPagarParcelaEspecificaLinkPagamentoOperationCompleted(object arg) {
            if ((this.PagarParcelaEspecificaLinkPagamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PagarParcelaEspecificaLinkPagamentoCompleted(this, new PagarParcelaEspecificaLinkPagamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ABEC.SIGA.WEBSERVICE/PagarBoletoVencidoCartao", RequestNamespace="ABEC.SIGA.WEBSERVICE", ResponseNamespace="ABEC.SIGA.WEBSERVICE", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PagarBoletoVencidoCartao(int idEmpresa, int idAluno, string idTurma, Cartao cartao, int numParcela) {
            object[] results = this.Invoke("PagarBoletoVencidoCartao", new object[] {
                        idEmpresa,
                        idAluno,
                        idTurma,
                        cartao,
                        numParcela});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PagarBoletoVencidoCartaoAsync(int idEmpresa, int idAluno, string idTurma, Cartao cartao, int numParcela) {
            this.PagarBoletoVencidoCartaoAsync(idEmpresa, idAluno, idTurma, cartao, numParcela, null);
        }
        
        /// <remarks/>
        public void PagarBoletoVencidoCartaoAsync(int idEmpresa, int idAluno, string idTurma, Cartao cartao, int numParcela, object userState) {
            if ((this.PagarBoletoVencidoCartaoOperationCompleted == null)) {
                this.PagarBoletoVencidoCartaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPagarBoletoVencidoCartaoOperationCompleted);
            }
            this.InvokeAsync("PagarBoletoVencidoCartao", new object[] {
                        idEmpresa,
                        idAluno,
                        idTurma,
                        cartao,
                        numParcela}, this.PagarBoletoVencidoCartaoOperationCompleted, userState);
        }
        
        private void OnPagarBoletoVencidoCartaoOperationCompleted(object arg) {
            if ((this.PagarBoletoVencidoCartaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PagarBoletoVencidoCartaoCompleted(this, new PagarBoletoVencidoCartaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ABEC.SIGA.WEBSERVICE")]
    public partial class AlunoDTO {
        
        private int idAlunoField;
        
        private string nomeField;
        
        private string cpfField;
        
        private string telefoneResidencialField;
        
        private string telefoneCelularField;
        
        private string telefoneComercialField;
        
        private string nomePaiField;
        
        private string nomeMaeField;
        
        private int escolaridadeField;
        
        private string logradouroField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string cepField;
        
        private int idProcedenciaField;
        
        private System.DateTime dataNascimentoField;
        
        private string estadoCivilField;
        
        private string cidadeNaturalidadeField;
        
        private string dddTelefoneResidencialField;
        
        private string dddTelefoneCelularField;
        
        private string dddTelefoneComercialField;
        
        private char sexoField;
        
        private int idTipoAlunoField;
        
        private int idFormacaoField;
        
        private string emailField;
        
        private int idCidadeField;
        
        private string idUFField;
        
        private ResponsavelDTO responsavelField;
        
        private int idEmpresaOrigemField;
        
        private bool flgNaoReceberEmailsField;
        
        private string numeroField;
        
        /// <remarks/>
        public int IdAluno {
            get {
                return this.idAlunoField;
            }
            set {
                this.idAlunoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string TelefoneResidencial {
            get {
                return this.telefoneResidencialField;
            }
            set {
                this.telefoneResidencialField = value;
            }
        }
        
        /// <remarks/>
        public string TelefoneCelular {
            get {
                return this.telefoneCelularField;
            }
            set {
                this.telefoneCelularField = value;
            }
        }
        
        /// <remarks/>
        public string TelefoneComercial {
            get {
                return this.telefoneComercialField;
            }
            set {
                this.telefoneComercialField = value;
            }
        }
        
        /// <remarks/>
        public string NomePai {
            get {
                return this.nomePaiField;
            }
            set {
                this.nomePaiField = value;
            }
        }
        
        /// <remarks/>
        public string NomeMae {
            get {
                return this.nomeMaeField;
            }
            set {
                this.nomeMaeField = value;
            }
        }
        
        /// <remarks/>
        public int Escolaridade {
            get {
                return this.escolaridadeField;
            }
            set {
                this.escolaridadeField = value;
            }
        }
        
        /// <remarks/>
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        public int IdProcedencia {
            get {
                return this.idProcedenciaField;
            }
            set {
                this.idProcedenciaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataNascimento {
            get {
                return this.dataNascimentoField;
            }
            set {
                this.dataNascimentoField = value;
            }
        }
        
        /// <remarks/>
        public string EstadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
            }
        }
        
        /// <remarks/>
        public string CidadeNaturalidade {
            get {
                return this.cidadeNaturalidadeField;
            }
            set {
                this.cidadeNaturalidadeField = value;
            }
        }
        
        /// <remarks/>
        public string DddTelefoneResidencial {
            get {
                return this.dddTelefoneResidencialField;
            }
            set {
                this.dddTelefoneResidencialField = value;
            }
        }
        
        /// <remarks/>
        public string DddTelefoneCelular {
            get {
                return this.dddTelefoneCelularField;
            }
            set {
                this.dddTelefoneCelularField = value;
            }
        }
        
        /// <remarks/>
        public string DddTelefoneComercial {
            get {
                return this.dddTelefoneComercialField;
            }
            set {
                this.dddTelefoneComercialField = value;
            }
        }
        
        /// <remarks/>
        public char Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public int IdTipoAluno {
            get {
                return this.idTipoAlunoField;
            }
            set {
                this.idTipoAlunoField = value;
            }
        }
        
        /// <remarks/>
        public int IdFormacao {
            get {
                return this.idFormacaoField;
            }
            set {
                this.idFormacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int IdCidade {
            get {
                return this.idCidadeField;
            }
            set {
                this.idCidadeField = value;
            }
        }
        
        /// <remarks/>
        public string IdUF {
            get {
                return this.idUFField;
            }
            set {
                this.idUFField = value;
            }
        }
        
        /// <remarks/>
        public ResponsavelDTO Responsavel {
            get {
                return this.responsavelField;
            }
            set {
                this.responsavelField = value;
            }
        }
        
        /// <remarks/>
        public int IdEmpresaOrigem {
            get {
                return this.idEmpresaOrigemField;
            }
            set {
                this.idEmpresaOrigemField = value;
            }
        }
        
        /// <remarks/>
        public bool FlgNaoReceberEmails {
            get {
                return this.flgNaoReceberEmailsField;
            }
            set {
                this.flgNaoReceberEmailsField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ABEC.SIGA.WEBSERVICE")]
    public partial class ResponsavelDTO {
        
        private int idResponsavelField;
        
        private string nomeField;
        
        private System.Nullable<System.DateTime> nascimentoField;
        
        private string estadoCivilField;
        
        private System.Nullable<char> sexoField;
        
        private string numeroField;
        
        private string enderecoField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string cepField;
        
        private string cpfField;
        
        private int idCidadeField;
        
        private string idUFField;
        
        private string dDDTelefoneCelularField;
        
        private string telefoneCelularField;
        
        private string dDDTelefoneResidencialField;
        
        private string telefoneResidencialField;
        
        private string dDDTelefoneComercialField;
        
        private string telefoneComercialField;
        
        private bool flgInterfaceSAPField;
        
        private string numeroResidencialField;
        
        private string emailField;
        
        /// <remarks/>
        public int IdResponsavel {
            get {
                return this.idResponsavelField;
            }
            set {
                this.idResponsavelField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Nascimento {
            get {
                return this.nascimentoField;
            }
            set {
                this.nascimentoField = value;
            }
        }
        
        /// <remarks/>
        public string EstadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<char> Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public int IdCidade {
            get {
                return this.idCidadeField;
            }
            set {
                this.idCidadeField = value;
            }
        }
        
        /// <remarks/>
        public string IdUF {
            get {
                return this.idUFField;
            }
            set {
                this.idUFField = value;
            }
        }
        
        /// <remarks/>
        public string DDDTelefoneCelular {
            get {
                return this.dDDTelefoneCelularField;
            }
            set {
                this.dDDTelefoneCelularField = value;
            }
        }
        
        /// <remarks/>
        public string TelefoneCelular {
            get {
                return this.telefoneCelularField;
            }
            set {
                this.telefoneCelularField = value;
            }
        }
        
        /// <remarks/>
        public string DDDTelefoneResidencial {
            get {
                return this.dDDTelefoneResidencialField;
            }
            set {
                this.dDDTelefoneResidencialField = value;
            }
        }
        
        /// <remarks/>
        public string TelefoneResidencial {
            get {
                return this.telefoneResidencialField;
            }
            set {
                this.telefoneResidencialField = value;
            }
        }
        
        /// <remarks/>
        public string DDDTelefoneComercial {
            get {
                return this.dDDTelefoneComercialField;
            }
            set {
                this.dDDTelefoneComercialField = value;
            }
        }
        
        /// <remarks/>
        public string TelefoneComercial {
            get {
                return this.telefoneComercialField;
            }
            set {
                this.telefoneComercialField = value;
            }
        }
        
        /// <remarks/>
        public bool FlgInterfaceSAP {
            get {
                return this.flgInterfaceSAPField;
            }
            set {
                this.flgInterfaceSAPField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroResidencial {
            get {
                return this.numeroResidencialField;
            }
            set {
                this.numeroResidencialField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Message.SisPag.Braspag")]
    public partial class Cartao {
        
        private int idCartaoField;
        
        private System.Nullable<int> idCartaoOrigemField;
        
        private TipoBandeiraBraspag tipoBandeiraBraspagField;
        
        private string nomeBandeiraField;
        
        private string nomeCompradorField;
        
        private string numeroCartaoField;
        
        private string numeroCodigoSegurancaField;
        
        private string dataValidadeCartaoField;
        
        private string nomeImpressoCartaoField;
        
        private bool ativoField;
        
        private System.DateTime dataRegistroField;
        
        private System.Nullable<int> idUsuarioField;
        
        private string textoGenerico1Field;
        
        private string textoGenerico2Field;
        
        /// <remarks/>
        public int IdCartao {
            get {
                return this.idCartaoField;
            }
            set {
                this.idCartaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdCartaoOrigem {
            get {
                return this.idCartaoOrigemField;
            }
            set {
                this.idCartaoOrigemField = value;
            }
        }
        
        /// <remarks/>
        public TipoBandeiraBraspag TipoBandeiraBraspag {
            get {
                return this.tipoBandeiraBraspagField;
            }
            set {
                this.tipoBandeiraBraspagField = value;
            }
        }
        
        /// <remarks/>
        public string NomeBandeira {
            get {
                return this.nomeBandeiraField;
            }
            set {
                this.nomeBandeiraField = value;
            }
        }
        
        /// <remarks/>
        public string NomeComprador {
            get {
                return this.nomeCompradorField;
            }
            set {
                this.nomeCompradorField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroCartao {
            get {
                return this.numeroCartaoField;
            }
            set {
                this.numeroCartaoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroCodigoSeguranca {
            get {
                return this.numeroCodigoSegurancaField;
            }
            set {
                this.numeroCodigoSegurancaField = value;
            }
        }
        
        /// <remarks/>
        public string DataValidadeCartao {
            get {
                return this.dataValidadeCartaoField;
            }
            set {
                this.dataValidadeCartaoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeImpressoCartao {
            get {
                return this.nomeImpressoCartaoField;
            }
            set {
                this.nomeImpressoCartaoField = value;
            }
        }
        
        /// <remarks/>
        public bool Ativo {
            get {
                return this.ativoField;
            }
            set {
                this.ativoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataRegistro {
            get {
                return this.dataRegistroField;
            }
            set {
                this.dataRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string TextoGenerico1 {
            get {
                return this.textoGenerico1Field;
            }
            set {
                this.textoGenerico1Field = value;
            }
        }
        
        /// <remarks/>
        public string TextoGenerico2 {
            get {
                return this.textoGenerico2Field;
            }
            set {
                this.textoGenerico2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Message.SisPag.Braspag")]
    public enum TipoBandeiraBraspag {
        
        /// <remarks/>
        Visa,
        
        /// <remarks/>
        MasterCard,
        
        /// <remarks/>
        AmericanExpress,
        
        /// <remarks/>
        Dinners,
        
        /// <remarks/>
        EloCredito,
        
        /// <remarks/>
        HiperCard,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ABEC.SIGA.WEBSERVICE")]
    public partial class LinkContratoDTO {
        
        private string urlField;
        
        private string mensagemErroField;
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string MensagemErro {
            get {
                return this.mensagemErroField;
            }
            set {
                this.mensagemErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ABEC.SIGA.WEBSERVICE")]
    public partial class SituacaoFinanceiraAlunoDTO {
        
        private int numeroParcelaField;
        
        private decimal valorContaReceberField;
        
        private System.DateTime dataVencimentoField;
        
        private int idFormaPagamentoField;
        
        private string nomeFormaPagamentoField;
        
        private bool pagoField;
        
        private string urlBoletoField;
        
        private string numCpfField;
        
        private bool boletoAcordoVCOMField;
        
        private string bancoField;
        
        /// <remarks/>
        public int NumeroParcela {
            get {
                return this.numeroParcelaField;
            }
            set {
                this.numeroParcelaField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorContaReceber {
            get {
                return this.valorContaReceberField;
            }
            set {
                this.valorContaReceberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataVencimento {
            get {
                return this.dataVencimentoField;
            }
            set {
                this.dataVencimentoField = value;
            }
        }
        
        /// <remarks/>
        public int IdFormaPagamento {
            get {
                return this.idFormaPagamentoField;
            }
            set {
                this.idFormaPagamentoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeFormaPagamento {
            get {
                return this.nomeFormaPagamentoField;
            }
            set {
                this.nomeFormaPagamentoField = value;
            }
        }
        
        /// <remarks/>
        public bool Pago {
            get {
                return this.pagoField;
            }
            set {
                this.pagoField = value;
            }
        }
        
        /// <remarks/>
        public string UrlBoleto {
            get {
                return this.urlBoletoField;
            }
            set {
                this.urlBoletoField = value;
            }
        }
        
        /// <remarks/>
        public string NumCpf {
            get {
                return this.numCpfField;
            }
            set {
                this.numCpfField = value;
            }
        }
        
        /// <remarks/>
        public bool BoletoAcordoVCOM {
            get {
                return this.boletoAcordoVCOMField;
            }
            set {
                this.boletoAcordoVCOMField = value;
            }
        }
        
        /// <remarks/>
        public string Banco {
            get {
                return this.bancoField;
            }
            set {
                this.bancoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ManterAlunoCompletedEventHandler(object sender, ManterAlunoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ManterAlunoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ManterAlunoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ObterAlunoSigaCompletedEventHandler(object sender, ObterAlunoSigaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterAlunoSigaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterAlunoSigaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ObterSituacaoFinanceiraCompletedEventHandler(object sender, ObterSituacaoFinanceiraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterSituacaoFinanceiraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterSituacaoFinanceiraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SituacaoFinanceiraAlunoDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SituacaoFinanceiraAlunoDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ObterLinkContratoAlunoCompletedEventHandler(object sender, ObterLinkContratoAlunoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterLinkContratoAlunoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterLinkContratoAlunoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LinkContratoDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LinkContratoDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void PagarLinkPagamentoCompletedEventHandler(object sender, PagarLinkPagamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PagarLinkPagamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PagarLinkPagamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void TrocarCartaoLinkPagamentoCompletedEventHandler(object sender, TrocarCartaoLinkPagamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrocarCartaoLinkPagamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TrocarCartaoLinkPagamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void PagarParcelaEspecificaLinkPagamentoCompletedEventHandler(object sender, PagarParcelaEspecificaLinkPagamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PagarParcelaEspecificaLinkPagamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PagarParcelaEspecificaLinkPagamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void PagarBoletoVencidoCartaoCompletedEventHandler(object sender, PagarBoletoVencidoCartaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PagarBoletoVencidoCartaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PagarBoletoVencidoCartaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591